apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80

    - name: busybox
      image: busybox
      command: ["sleep", "3600"]